"""empty message

Revision ID: 06cbd48c4e1a
Revises: 0c45baeee82c
Create Date: 2022-06-22 14:51:32.467217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06cbd48c4e1a'
down_revision = '0c45baeee82c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('start_date', sa.String(), nullable=True))
    op.add_column('trips', sa.Column('end_date', sa.String(), nullable=True))
    op.drop_column('trips', 'date_end')
    op.drop_column('trips', 'date_start')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('date_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('date_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('trips', 'end_date')
    op.drop_column('trips', 'start_date')
    # ### end Alembic commands ###
