"""empty message

Revision ID: 0c45baeee82c
Revises: 
Create Date: 2022-06-21 11:04:24.323982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c45baeee82c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('date_start', sa.DateTime(), nullable=True))
    op.add_column('trips', sa.Column('date_end', sa.DateTime(), nullable=True))
    op.drop_column('trips', 'length')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('length', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('trips', 'date_end')
    op.drop_column('trips', 'date_start')
    # ### end Alembic commands ###
