"""empty message

Revision ID: c77bd2c40b26
Revises: e8a77518c142
Create Date: 2022-06-22 16:20:30.745282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c77bd2c40b26'
down_revision = 'e8a77518c142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('start_date', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('end_date', sa.Float(), nullable=True))
    op.drop_column('trips', 'date_end')
    op.drop_column('trips', 'date_start')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('date_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('date_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('trips', 'end_date')
    op.drop_column('trips', 'start_date')
    # ### end Alembic commands ###
