"""empty message

Revision ID: e8a77518c142
Revises: 06cbd48c4e1a
Create Date: 2022-06-22 15:51:48.530017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a77518c142'
down_revision = '06cbd48c4e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('date_start', sa.DateTime(), nullable=True))
    op.add_column('trips', sa.Column('date_end', sa.DateTime(), nullable=True))
    op.drop_column('trips', 'start_date')
    op.drop_column('trips', 'end_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('end_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('start_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('trips', 'date_end')
    op.drop_column('trips', 'date_start')
    # ### end Alembic commands ###
